# Generated by Django 5.1.2 on 2024-10-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_userrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
